# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ :name => 'Chicago' }, { :name => 'Copenhagen' }])
#   Mayor.create(:name => 'Daley', :city => cities.first)
Sector.delete_all
Regio.delete_all
Sector.create(:sectorId => '1',
  :sectorName => 'Aannemers')

Sector.create(:sectorId => '2',
  :sectorName => 'Aanwervingsbureau')

Sector.create(:sectorId => '3',
  :sectorName => 'Accountants')
Sector.create(:sectorId =>'4',
  :sectorName => 'Aandrijving')
Sector.create(:sectorId =>'5',
  :sectorName => 'Aanhangwagens')
Sector.create(:sectorId =>'6',
  :sectorName => 'Voeding')
Sector.create(:sectorId =>'7',
  :sectorName => 'Advocaten')
Sector.create(:sectorId =>'8',
  :sectorName => 'sanitair')
Sector.create(:sectorId =>'9',
  :sectorName => 'aluminium')
Sector.create(:sectorId =>'10',
  :sectorName => 'apotheker')
Sector.create(:sectorId =>'11',
  :sectorName => 'artiesten')
Sector.create(:sectorId =>'12',
  :sectorName => 'Auto')
Sector.create(:sectorId =>'13',
  :sectorName => 'Baby')
Sector.create(:sectorId =>'14',
  :sectorName => 'cafe')
Sector.create(:sectorId =>'15',
  :sectorName => 'casino')
Sector.create(:sectorId =>'16',
  :sectorName => 'dokter')
Sector.create(:sectorId =>'17',
  :sectorName => 'deegwaren')
Sector.create(:sectorId =>'18',
  :sectorName => 'detectives')
Sector.create(:sectorId =>'19',
  :sectorName => 'houtbewerking')
Sector.create(:sectorId =>'20',
  :sectorName => 'juwelier')
Sector.create(:sectorId =>'21',
  :sectorName => 'doe-het-zelf')
Sector.create(:sectorId =>'22',
  :sectorName => 'tankstation')
Sector.create(:sectorId =>'23',
  :sectorName => 'elektricien')
Sector.create(:sectorId =>'24',
  :sectorName => 'elektro')
Sector.create(:sectorId =>'25',
  :sectorName => 'restaurant')
Sector.create(:sectorId =>'26',
  :sectorName => 'eetcafe')
Sector.create(:sectorId =>'27',
  :sectorName => 'fietsen')
Sector.create(:sectorId =>'28',
  :sectorName => 'feestartikelen')
Sector.create(:sectorId =>'29',
  :sectorName => 'foto')
Sector.create(:sectorId =>'30',
  :sectorName => 'fitness')
Sector.create(:sectorId =>'31',
  :sectorName => 'frituren')
Sector.create(:sectorId =>'32',
  :sectorName => 'garages')
Sector.create(:sectorId =>'33',
  :sectorName => 'gas')
Sector.create(:sectorId =>'34',
  :sectorName => 'geluid')
Sector.create(:sectorId =>'35',
  :sectorName => 'licht')
Sector.create(:sectorId =>'36',
  :sectorName => 'metaal')
Sector.create(:sectorId =>'37',
  :sectorName => 'bouw')
Sector.create(:sectorId =>'38',
  :sectorName => 'tuincenter')
Sector.create(:sectorId =>'39',
  :sectorName => 'tuin')
Sector.create(:sectorId =>'40',
  :sectorName => 'GSM')
Sector.create(:sectorId =>'41',
  :sectorName => 'Computers')
Sector.create(:sectorId =>'42',
  :sectorName => 'groenten & fruit')
Sector.create(:sectorId =>'43',
  :sectorName => 'kapsalon')
Sector.create(:sectorId =>'44',
  :sectorName => 'schoenen')
Sector.create(:sectorId =>'45',
  :sectorName => 'energie')
Sector.create(:sectorId =>'46',
  :sectorName => 'hout')
Sector.create(:sectorId =>'47',
  :sectorName => 'huisdieren')
Sector.create(:sectorId =>'48',
  :sectorName => 'huishouden')
Sector.create(:sectorId =>'49',
  :sectorName => 'immobilien')
Sector.create(:sectorId =>'50',
  :sectorName => 'internet')
Sector.create(:sectorId =>'51',
  :sectorName => 'informatica')
Sector.create(:sectorId =>'52',
  :sectorName => 'isolatie')
Sector.create(:sectorId =>'53',
  :sectorName => 'interieur')
Sector.create(:sectorId =>'54',
  :sectorName => 'kachels')
Sector.create(:sectorId =>'55',
  :sectorName => 'Kampeerterrein')
Sector.create(:sectorId =>'56',
  :sectorName => 'keukens')
Sector.create(:sectorId =>'57',
  :sectorName => 'kinderanimatie')
Sector.create(:sectorId =>'58',
  :sectorName => 'koper')
Sector.create(:sectorId =>'59',
  :sectorName => 'schilder')
Sector.create(:sectorId =>'60',
  :sectorName => 'reclame')
Sector.create(:sectorId =>'61',
  :sectorName => 'video')
Sector.create(:sectorId =>'62',
  :sectorName => 'muziek')
Sector.create(:sectorId =>'63',
  :sectorName => 'sport')
Sector.create(:sectorId =>'64',
  :sectorName => 'notarissen')
Sector.create(:sectorId =>'65',
  :sectorName => 'onderwijs')
Sector.create(:sectorId =>'66',
  :sectorName => 'rusthuizen')
Sector.create(:sectorId =>'67',
  :sectorName => 'scheepvaart')
Sector.create(:sectorId =>'68',
  :sectorName => 'tabak')
Sector.create(:sectorId =>'69',
  :sectorName => 'snack-bar')
Sector.create(:sectorId =>'70',
  :sectorName => 'software')
Sector.create(:sectorId =>'71',
  :sectorName => 'tandarts')
Sector.create(:sectorId =>'72',
  :sectorName => 'televisie')
Sector.create(:sectorId =>'73',
  :sectorName => 'veehandel')
Sector.create(:sectorId =>'74',
  :sectorName => 'transport')
Sector.create(:sectorId =>'75',
  :sectorName => 'drank')
Sector.create(:sectorId =>'76',
  :sectorName => 'eten')
Sector.create(:sectorId =>'77',
  :sectorName => 'vrije tijd')
Sector.create(:sectorId =>'78',
  :sectorName => 'onderhoud')
Sector.create(:sectorId =>'79',
  :sectorName => 'drinken')

Regio.create(:regioId => '1',
  :regioName => 'West-Vlaanderen')
Regio.create(:regioId => '2',
  :regioName => 'Oost-Vlaanderen')
Regio.create(:regioId => '3',
  :regioName => 'Antwerpen')
Regio.create(:regioId => '4',
  :regioName => 'Limburg')
Regio.create(:regioId => '5',
  :regioName => 'Vlaams-Brabant')
Regio.create(:regioId => '6',
  :regioName => 'Brussel')
Regio.create(:regioId => '7',
  :regioName => 'Waals-Brabant')
Regio.create(:regioId => '8',
  :regioName => 'Henegouwen')
Regio.create(:regioId => '9',
  :regioName => 'Luxemburg')
Regio.create(:regioId => '10',
  :regioName => 'Namen')
Regio.create(:regioId => '11',
  :regioName => 'Luik')
